apiVersion: v1
kind: Service
metadata:
  name: slalite-service-latest
  namespace: default
spec:
  selector:
    app: slalite-latest
  ports:
  - name: slalite-latest
    port: 8094
    protocol: TCP
    targetPort: 8094
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
